# Generated by Django 5.2.8 on 2025-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdata',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='desk_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
