# Generated by Django 5.2.8 on 2025-11-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_timestamp_usersdata_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdata',
            old_name='desk_name',
            new_name='assignDesk',
        ),
        migrations.RenameField(
            model_name='usersdata',
            old_name='phone',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usersdata',
            old_name='email',
            new_name='userId',
        ),
    ]
