# Generated by Django 5.2.8 on 2025-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_desk_name_usersdata_assigndesk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='userId',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
