# Generated by Django 5.2.8 on 2025-11-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='mode',
            field=models.CharField(default='Onspot', max_length=20),
        ),
    ]
