# Generated by Django 5.2.8 on 2025-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_participant_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='mode',
            field=models.CharField(default='onspot', max_length=20),
        ),
    ]
