# Generated by Django 5.2.8 on 2025-11-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_qrregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_code',
            field=models.CharField(default='NA', max_length=100, unique=True),
        ),
    ]
