# Generated by Django 5.2.8 on 2025-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_participant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.CharField(max_length=100),
        ),
    ]
