# Generated by Django 5.2.8 on 2025-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_participant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
